// ─── Auto-generated by generate-config.js ─────────────────────────────
// Do not edit manually. Re-run `node generate-config.js` to regenerate.
// These are Supabase public (anon) credentials — safe to serve to the browser.
// Security is enforced via Supabase Row Level Security policies.
window.SUPABASE_URL      = "https://dnsdftescwyepyospezg.supabase.co";
window.SUPABASE_ANON_KEY = window.SUPABASE_ANON_KEY = "sb_publishable_Tz6vcwt_IK4aHI1ylaAt1A_aQfTqWq_";
window.ADMIN_EMAIL       = window.ADMIN_EMAIL = "adedejimayowa27@gmail.com";
