/**
 * generate-config.js
 * Reads Supabase credentials from environment variables and writes
 * src/config.js so the static frontend can access them safely.
 * The anon key is designed to be public — Row Level Security on Supabase
 * is the actual security boundary, not key secrecy.
 *
 * Run via: node generate-config.js
 */

const fs           = require('fs');
const { execSync } = require('child_process');
const path         = require('path');

const SUPABASE_URL      = process.env.SUPABASE_URL      || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';
const ADMIN_EMAIL       = process.env.ADMIN_EMAIL       || '';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.warn(
        '\n⚠️  SUPABASE_URL or SUPABASE_ANON_KEY is not set.\n' +
        '   The app will load but Supabase features will not work.\n' +
        '   Set these as Replit Secrets and restart the workflow.\n'
    );
}

const config = `// ─── Auto-generated by generate-config.js ─────────────────────────────
// Do not edit manually. Re-run \`node generate-config.js\` to regenerate.
// These are Supabase public (anon) credentials — safe to serve to the browser.
// Security is enforced via Supabase Row Level Security policies.
window.SUPABASE_URL      = ${JSON.stringify(SUPABASE_URL)};
window.SUPABASE_ANON_KEY = ${JSON.stringify(SUPABASE_ANON_KEY)};
window.ADMIN_EMAIL       = ${JSON.stringify(ADMIN_EMAIL)};
`;

const configPath = path.join(__dirname, 'src', 'config.js');
fs.writeFileSync(configPath, config, 'utf8');
console.log('✓ src/config.js written from environment variables.');
console.log(`  SUPABASE_URL      : ${SUPABASE_URL      ? '✓ set' : '✗ missing'}`);
console.log(`  SUPABASE_ANON_KEY : ${SUPABASE_ANON_KEY ? '✓ set' : '✗ missing'}`);
console.log(`  ADMIN_EMAIL       : ${ADMIN_EMAIL       ? '✓ set' : '✗ missing'}`);
console.log('\nStarting static file server on port 5000…\n');

execSync('npx --yes serve src -p 5000 -s', { stdio: 'inherit' });
